# Generated by Django 5.1 on 2024-08-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TODO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todo'),
        ),
    ]
